apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  name: default-gitsource
  labels:
    codefresh.io/entity: 'git-source'
    codefresh.io/internal: 'false'
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: ${repoUrl}
    path: ${repoPath}
    targetRevision: ${repoBranch}
    directory:
      include: '*'
      exclude: ''
      recurse: true
  destination:
    namespace: ${namespace}
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true